"""Stage 7: Export fused track data as browser-ready JS and JSON files.

Separated from fusion — takes FusedTrackData objects and writes:
- track_XX.json (pure data)
- track_XX.js (browser-loadable wrapper with window.albumData)
- albums_index.json + albums_index.js
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from chak.config import PipelineConfig
from chak.schemas import FusedTrackData
from chak.utils.io import ensure_dir, load_json, write_json

logger = logging.getLogger(__name__)


def write_track_files(
    album_dir: Path,
    album_id: str,
    track_data: FusedTrackData,
) -> None:
    """Write a single track's JS and JSON data files."""
    data_dir = album_dir / "data"
    ensure_dir(data_dir)

    track_id = track_data.id
    serialized = track_data.model_dump()

    # Write pure JSON
    json_path = data_dir / f"{track_id}.json"
    write_json(json_path, serialized)

    # Write browser-loadable JS wrapper
    js_path = data_dir / f"{track_id}.js"
    json_str = json.dumps(serialized, indent=4, ensure_ascii=False)
    # Sanitize variable name (hyphens in variant IDs like T1-2-3a)
    var_name = track_id.replace("-", "_") + "_data"
    js_content = (
        f"// Auto-generated by chak pipeline\n"
        f"var {var_name} = {json_str};\n"
        f'window.albumData = window.albumData || {{}};\n'
        f'window.albumData["{album_id}"] = window.albumData["{album_id}"] || {{}};\n'
        f'window.albumData["{album_id}"]["{track_id}"] = {var_name};\n'
    )
    with open(js_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    logger.info("Wrote %s and %s", json_path.name, js_path.name)


def export_album_tracks(
    album_dir: Path,
    album_id: str,
    fused_tracks: list[FusedTrackData],
) -> None:
    """Write JS + JSON files for all fused tracks in an album."""
    for track_data in fused_tracks:
        write_track_files(album_dir, album_id, track_data)
    logger.info("Exported %d track files for album %s", len(fused_tracks), album_id)


def generate_albums_index(config: PipelineConfig) -> None:
    """Scan albums/*/album_config.json and write index files.

    Generates:
    - albums/albums_index.json (for tooling)
    - js/albums_index.js (for browser, defines window.albumRegistry)
    """
    project_root = config.project_root
    albums_dir = project_root / "albums"

    if not albums_dir.is_dir():
        logger.warning("albums/ directory not found; skipping index generation.")
        return

    index: list[dict[str, Any]] = []

    for entry_dir in sorted(albums_dir.iterdir()):
        if not entry_dir.is_dir():
            continue
        cfg_path = entry_dir / "album_config.json"
        if not cfg_path.exists():
            continue

        cfg = load_json(cfg_path)
        index.append({
            "album_id": cfg.get("album_id", entry_dir.name),
            "title": cfg.get("title", entry_dir.name),
            "description": cfg.get("description", ""),
            "config": cfg,
        })

    # Sort: prefer albums with built data (data/track_01.js exists)
    def has_built_data(e: dict[str, Any]) -> bool:
        aid = e.get("album_id", "")
        return (albums_dir / aid / "data" / "track_01.js").is_file()

    index.sort(key=lambda e: (0 if has_built_data(e) else 1, e.get("album_id", "")))

    # Write JSON index
    json_path = albums_dir / "albums_index.json"
    write_json(json_path, index)
    logger.info("Wrote albums_index.json -> %s", json_path)

    # Write JS index for browser (CORS/file:// friendly)
    js_dir = project_root / "js"
    ensure_dir(js_dir)
    js_path = js_dir / "albums_index.js"
    with open(js_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by chak pipeline\n")
        f.write("window.albumRegistry = ")
        json.dump(index, f, indent=4, ensure_ascii=False)
        f.write(";\n")
    logger.info("Wrote albums_index.js -> %s", js_path)
